---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: centos-6.4

suites:
  - name: server
    run_list:
      - recipe[riemann::default]
    attributes:

  - name: dashboard
    run_list:
      - recipe[riemann::dashboard]
    attributes:
